/*
 * Copyright (c) 2022  JsonGenerated by FoxesWorld
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package foxesworld.hardcontent.dynamic.JsonGenerated;

import foxesworld.hardcontent.dynamic.JsonGenerated.block.GenerateBlock;

import java.io.File;

import static foxesworld.hardcontent.cfg.Environment.*;
import static foxesworld.hardcontent.methods.Utils.debugSend;

public class JsonGenerated {
    public static String bindDir = MODCFGDIR + File.separator + MODID + File.separator +  generatedDirName + File.separator;

    public JsonGenerated() {

    }

    public static void genBlock(String name) {
        prepareWorkSpace();
        GenerateBlock.generateBlock(name);
    }

    private static void prepareWorkSpace() {
        String[] renderFolders = {
                "item",
                "block",
                "blockstates",
                "recipes"};
        for (String folder : renderFolders) {
            File workFolder = new File(bindDir + folder);
            if (!workFolder.exists()) {
                debugSend("Filder does ot exists - " +folder);
                workFolder.mkdir();
            }
        }
    }


}
